### ISSUE TITLE
Add "make clean-data" to makefile

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#26]
Add "make clean-data" to the Makefile so that the data container can be removed to completely reset the development environment.

Update the README to add the make command.

**Comment by lhridley** [comment]
Please review PR #27 and merge if tests out ok.  Thanks!

**Comment by lrowang** [comment]
Tested `make clean-data` and saw that it successfully removed the `autismcasestudy_mysql-data` container/volume!

Merged PR and will close issue.
