### ISSUE TITLE
Create the Resource view

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#39]
Create a view that displays resources sorted by category and title. The category uses the taxonomy vocabulary set up earlier.

The views display will use a URL of 'resources".

Write your behat tests first, that test for the presence of the view at "resources".  Write tests to make sure a user with the various roles (anonymous user, authenticated user, staff, and site administrator) have access to the view page.  As before, you will want to write your tests before you start creating your view.

See page 248 for more details.

**Comment by lhridley** [comment]
I'm gonna push back just a bit here.  We need more tests on this issue.

Write some tests that insert dummy content. and test that the content appears in the correct sort order.  I looked at your view and you are missing the secondary sort on resource title, so that needs to be added, and you need to test for that.

I'm going to suggest that you create 8 pieces of content, two for each resource type, and test that they appear in the right order on the page.  Each piece of content will be wrapped in a div that will have a unique class name (views-row-1, views-row-2) that can be used to test that the resources on the page are appearing in the correct order.

Another test is to filter on the resource category by selecting a category from the dropdown, and making sure that the right resource items show on the page and that resources that do not match the selected resource category from the exposed filter are not appearing.

Finally, you can right a test to make sure the "read more" link takes users to the node when it is clicked.

**Comment by lrowang** [comment]
Duly noted! See updated PR.
