### ISSUE TITLE
Create your first custom module

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#4]
Depends on Issue #2 
Create a custom module in the modules/custom folder called "acs_master".

* Make sure it has .info, .module, and .install files, properly commented based on Drupal coding standards
* Modify the inline shell script in the Vagrantfile to enable the newly written custom module (hint: there's a drush command that will do this)

Submit a PR, and assign for review.

* Reference:  https://www.drupal.org/developing/modules/7
* ~~https://drushcommands.com/drush-8x/pm/pm-list/~~
* https://drushcommands.com/drush-8x/pm/pm-enable/

**Comment by lrowang** [comment]
Hi @lhridley ,

I submitted a [WIP] PR for you to review. I had some questions about commenting that I tagged in the [PR](https://github.com/savaslabs/autism-case-study/pull/14).

Talk soon!
Ro
