### ISSUE TITLE
Create an About Us page

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#41]
Create a basic page with the title About Us, and copy in the content from [this page](http://www.aane.org/about_aane/about_aane.html) using the first three paragraphs for your content.

Write your test to test for the presence of the page at "about-us", checks for the proper title on the page, and checks for key phrases from the content.  Make sure all of your roles can see the page.

See page 249 for more details.

**Comment by lrowang** [comment]
Those questions!

1. Is there any difference "execution-wise" to these 2 methods of setting fields within the entity_metatdata_wrapper? If not, is there a preference for one over the other? For example
>` $ewrapper->title->set('About Us');`
> vs
> `$wrapper->title = 'My new title';`
