### ISSUE TITLE
Create two roles, and assign permissions to those roles

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#7]
Create the two required roles: 

**staff**

* permission to author and publish content
* permission to post and administer comments
* permission to administer the forums
* permission to create web forms
* permission to manage menus

**site administrator** 

*  has all permissions enabled.

Do the following:

- Write tests for the roles and associated permissions
- Demonstrate that the tests fail
- Create the roles and configure the permissions
- Demonstrate that the tests pass
- Generate a feature that contains the roles and permissions
- Write a hook_update_n() to enable the feature
- Create a PR

Resources:

* Chapter 3
* https://www.drupal.org/node/120614

**Comment by lrowang** [comment]
WIP [PR](https://github.com/savaslabs/autism-case-study/pull/31) generated!
